'use client';

import {
  ClassicyApp,
  ClassicyWindow,
  // @ts-ignore - runtime export, not in classicy's d.ts
  useAppManagerDispatch,
} from 'classicy';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect } from 'react';
// @ts-ignore - generated by Velite
import { posts as rawPosts } from '../../.velite';
import PostBody from './PostBody';

type Post = {
  title: string;
  subTitle?: string;
  date: string;
  tags: string[];
  slug: string;
  body: string;
  permalink: string;
};

const posts = (rawPosts as Post[])
  .slice()
  .sort((a, b) => b.date.localeCompare(a.date));

function slugFromPathname(pathname: string | null): string | null {
  if (!pathname) return null;
  const match = pathname.match(/^\/posts\/([^/]+)/);
  return match ? match[1] : null;
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

export default function BlogWindow({ initialSlug }: { initialSlug: string }) {
  const router = useRouter();
  const pathname = usePathname();
  const dispatch = useAppManagerDispatch();

  useEffect(() => {
    dispatch({
      type: 'ClassicyAppOpen',
      app: { id: 'blog', name: 'Blog', icon: '' },
    });
  }, [dispatch]);

  const urlSlug = slugFromPathname(pathname);
  const selectedSlug = urlSlug ?? initialSlug;

  const selected =
    posts.find((p) => p.slug === selectedSlug) ?? posts[0] ?? null;

  const handleSelect = (slug: string) => {
    router.push(`/posts/${slug}`);
  };

  return (
    <ClassicyApp
      id="blog"
      name="Blog"
      icon=""
      noDesktopIcon
      defaultWindow="blog.main"
    >
      <ClassicyWindow
        id="blog.main"
        appId="blog"
        title="Blog"
        initialSize={[720, 480]}
        initialPosition={[120, 80]}
        defaultWindow
      >
        <div className="blogWindowLayout" data-testid="blog-window">
          <nav className="blogSidebar" aria-label="Posts">
            <ul>
              {posts.map((post) => {
                const isActive = post.slug === selectedSlug;
                return (
                  <li key={post.slug}>
                    <button
                      type="button"
                      data-testid={`post-link-${post.slug}`}
                      data-active={isActive ? 'true' : 'false'}
                      className={
                        isActive
                          ? 'blogSidebarItem blogSidebarItemActive'
                          : 'blogSidebarItem'
                      }
                      onClick={() => handleSelect(post.slug)}
                    >
                      <span className="blogSidebarTitle">{post.title}</span>
                      <span className="blogSidebarDate">
                        {formatDate(post.date)}
                      </span>
                    </button>
                  </li>
                );
              })}
            </ul>
          </nav>
          <section className="blogReadingPane" aria-label="Post content">
            {selected ? (
              <article>
                <header className="blogPostHeader">
                  <h1 className="blogPostTitle">{selected.title}</h1>
                  {selected.subTitle ? (
                    <p className="blogPostSubtitle">{selected.subTitle}</p>
                  ) : null}
                  <p className="blogPostDate">{formatDate(selected.date)}</p>
                </header>
                <PostBody html={selected.body} />
              </article>
            ) : (
              <p>No posts yet.</p>
            )}
          </section>
        </div>
      </ClassicyWindow>
    </ClassicyApp>
  );
}
