'use client';

import {
  ClassicyApp,
  ClassicyWindow,
  // @ts-ignore - runtime export, not in classicy's d.ts
  useAppManagerDispatch,
} from 'classicy';
import { usePathname } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
// @ts-ignore - generated by Velite
import { posts as rawPosts } from '../../.velite';
import PostBody from './PostBody';
import { POST_LISTINGS_APP_ID } from './PostListingsWindow';

type Post = {
  title: string;
  subTitle?: string;
  date: string;
  tags: string[];
  slug: string;
  body: string;
  permalink: string;
};

const posts = (rawPosts as Post[])
  .slice()
  .sort((a, b) => b.date.localeCompare(a.date));

type ClassicyMenuItem = {
  id: string;
  title?: string;
  disabled?: boolean;
  onClickFunc?: () => void;
  menuChildren?: ClassicyMenuItem[];
};

type ZoomMode = 'normal' | 'full';

function slugFromPathname(pathname: string | null): string | null {
  if (!pathname) return null;
  const match = pathname.match(/^\/posts\/([^/]+)/);
  return match ? match[1] : null;
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function PostReaderWindowInner({
  selectedSlug,
}: {
  selectedSlug: string;
}) {
  const dispatch = useAppManagerDispatch();
  const [zoom, setZoom] = useState<ZoomMode>('normal');

  useEffect(() => {
    document.documentElement.dataset.blogZoom = zoom;
    return () => {
      delete document.documentElement.dataset.blogZoom;
    };
  }, [zoom]);

  const selected =
    posts.find((p) => p.slug === selectedSlug) ?? posts[0] ?? null;

  const appMenu = useMemo<ClassicyMenuItem[]>(
    () => [
      {
        id: 'blog.file',
        title: 'File',
        menuChildren: [
          {
            id: 'blog.file.open',
            title: 'Open\u2026',
            onClickFunc: () => {
              dispatch({
                type: 'ClassicyAppOpen',
                app: {
                  id: POST_LISTINGS_APP_ID,
                  name: 'Posts',
                  icon: '',
                },
              });
              dispatch({
                type: 'ClassicyAppFocus',
                app: { id: POST_LISTINGS_APP_ID }
              });
            },
          },
        ],
      },
      {
        id: 'blog.edit',
        title: 'Edit',
        menuChildren: [
          {
            id: 'blog.edit.posts',
            title: 'Edit Posts',
            disabled: true,
          },
        ],
      },
      {
        id: 'blog.view',
        title: 'View',
        menuChildren: [
          {
            id: 'blog.view.normal',
            title: 'Normal',
            onClickFunc: () => setZoom('normal'),
          },
          {
            id: 'blog.view.full',
            title: 'Full Width',
            onClickFunc: () => setZoom('full'),
          },
        ],
      },
      {
        id: 'blog.help',
        title: 'Help',
        menuChildren: [
          {
            id: 'blog.help.help-me',
            title: 'Help me\u2026',
            onClickFunc: () => {
              window.open('https://www.google.com', '_blank');
            },
          },
        ],
      },
    ],
    [dispatch],
  );

  return (
    <ClassicyWindow
      id="blog.reader"
      appId="blog"
      title={selected ? selected.title : 'Blog'}
      initialSize={[1000, 720]}
      initialPosition={[0, 22]}
      resizable={false}
      zoomable={false}
      collapsable={false}
      defaultWindow
      appMenu={appMenu}
    >
      <div
        className="blogReadingPane"
        data-testid="blog-window"
        data-zoom={zoom}
      >
        {selected ? (
          <article>
            <header className="blogPostHeader">
              <h1 className="blogPostTitle">{selected.title}</h1>
              {selected.subTitle ? (
                <p className="blogPostSubtitle">{selected.subTitle}</p>
              ) : null}
              <p className="blogPostDate">{formatDate(selected.date)}</p>
            </header>
            <PostBody html={selected.body} />
          </article>
        ) : (
          <p>No posts yet.</p>
        )}
      </div>
    </ClassicyWindow>
  );
}

export default function PostReaderWindow({
  initialSlug,
}: {
  initialSlug: string;
}) {
  const pathname = usePathname();
  const dispatch = useAppManagerDispatch();

  useEffect(() => {
    dispatch({
      type: 'ClassicyAppOpen',
      app: { id: 'blog', name: 'Blog', icon: '' },
    });
  }, [dispatch]);

  const urlSlug = slugFromPathname(pathname);
  const selectedSlug = urlSlug ?? initialSlug;

  return (
    <ClassicyApp
      id="blog"
      name="Blog"
      icon=""
      noDesktopIcon
      defaultWindow="blog.reader"
    >
      <PostReaderWindowInner key={selectedSlug} selectedSlug={selectedSlug} />
    </ClassicyApp>
  );
}
