'use client';

import {
  ClassicyApp,
  ClassicyWindow,
} from 'classicy';
import { useRouter } from 'next/navigation';
// @ts-ignore - generated by Velite
import { posts as rawPosts } from '../../.velite';

type Post = {
  title: string;
  date: string;
  tags: string[];
  slug: string;
};

const posts = (rawPosts as Post[])
  .slice()
  .sort((a, b) => b.date.localeCompare(a.date));

export const POST_LISTINGS_APP_ID = 'postListings';
export const POST_LISTINGS_WINDOW_ID = 'postListings.main';

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function PostListingsTable() {
  const router = useRouter();

  return (
    <div className="postListingsContainer" data-testid="post-listings-window">
      <table className="postListingsTable">
        <thead>
          <tr>
            <th className="postListingsHeaderName">Name</th>
            <th className="postListingsHeaderDate">Date Added</th>
            <th className="postListingsHeaderTags">Tags</th>
          </tr>
        </thead>
        <tbody>
          {posts.map((post) => (
            <tr
              key={post.slug}
              className="postListingsRow"
              data-testid={`post-listing-${post.slug}`}
              onClick={() => router.push(`/posts/${post.slug}`)}
            >
              <td className="postListingsCellName">{post.title}</td>
              <td className="postListingsCellDate">{formatDate(post.date)}</td>
              <td className="postListingsCellTags">{post.tags.join(', ')}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function PostListingsWindow() {
  return (
    <ClassicyApp
      id={POST_LISTINGS_APP_ID}
      name="Posts"
      icon=""
      noDesktopIcon
      defaultWindow={POST_LISTINGS_WINDOW_ID}
    >
      <ClassicyWindow
        id={POST_LISTINGS_WINDOW_ID}
        appId={POST_LISTINGS_APP_ID}
        title="Posts"
        initialSize={[500, 300]}
        initialPosition={[250, 80]}
        resizable={false}
        zoomable={false}
        collapsable={false}
        defaultWindow
      >
        <PostListingsTable />
      </ClassicyWindow>
    </ClassicyApp>
  );
}
