'use client';

import {
  ClassicyApp,
  ClassicyIcons,
  ClassicyWindow,
} from 'classicy';
import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
// @ts-ignore - generated by Velite
import { posts as rawPosts } from '../../.velite';

type Post = {
  title: string;
  date: string;
  tags: string[];
  slug: string;
  body: string;
};

const posts = (rawPosts as Post[])
  .slice()
  .sort((a, b) => b.date.localeCompare(a.date));

export const POST_LISTINGS_APP_ID = 'postListings';
export const POST_LISTINGS_WINDOW_ID = 'postListings.main';

type SortKey = 'name' | 'date' | 'size';
type SortDir = 'asc' | 'desc';

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function byteSize(html: string): number {
  return new Blob([html]).size;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

function PostListingsTable() {
  const router = useRouter();
  const [sortKey, setSortKey] = useState<SortKey>('date');
  const [sortDir, setSortDir] = useState<SortDir>('desc');

  const postsWithSize = useMemo(
    () => posts.map((p) => ({ ...p, bytes: byteSize(p.body) })),
    [],
  );

  const sorted = useMemo(() => {
    const list = [...postsWithSize];
    const dir = sortDir === 'asc' ? 1 : -1;
    switch (sortKey) {
      case 'name':
        list.sort((a, b) => dir * a.title.localeCompare(b.title));
        break;
      case 'date':
        list.sort((a, b) => dir * a.date.localeCompare(b.date));
        break;
      case 'size':
        list.sort((a, b) => dir * (a.bytes - b.bytes));
        break;
    }
    return list;
  }, [postsWithSize, sortKey, sortDir]);

  const totalBytes = useMemo(
    () => postsWithSize.reduce((sum, p) => sum + p.bytes, 0),
    [postsWithSize],
  );

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortKey(key);
      setSortDir(key === 'name' ? 'asc' : 'desc');
    }
  };

  const sortIndicator = (key: SortKey) => {
    if (sortKey !== key) return null;
    return (
      <span className="postListingsSortIndicator">
        {sortDir === 'asc' ? '\u25B2' : '\u25BC'}
      </span>
    );
  };

  return (
    <div className="postListingsContainer" data-testid="post-listings-window">
      <div className="postListingsScrollArea">
        <table className="postListingsTable">
          <thead>
            <tr>
              <th
                className="postListingsHeaderName postListingsHeaderSortable"
                onClick={() => handleSort('name')}
              >
                Name{sortIndicator('name')}
              </th>
              <th
                className="postListingsHeaderDate postListingsHeaderSortable"
                onClick={() => handleSort('date')}
              >
                Date Modified{sortIndicator('date')}
              </th>
              <th
                className="postListingsHeaderSize postListingsHeaderSortable"
                onClick={() => handleSort('size')}
              >
                Size{sortIndicator('size')}
              </th>
              <th className="postListingsHeaderKind">Kind</th>
            </tr>
          </thead>
          <tbody>
            {sorted.map((post) => (
              <tr
                key={post.slug}
                className="postListingsRow"
                data-testid={`post-listing-${post.slug}`}
                onClick={() => router.push(`/posts/${post.slug}`)}
              >
                <td className="postListingsCellName">
                  <span className="postListingsCellNameContent">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={ClassicyIcons.system.files.document}
                      alt=""
                      className="postListingsCellNameIcon"
                    />
                    {post.title}
                  </span>
                </td>
                <td className="postListingsCellDate">
                  {formatDate(post.date)}
                </td>
                <td className="postListingsCellSize">
                  {formatBytes(post.bytes)}
                </td>
                <td className="postListingsCellKind">
                  {post.tags.join(', ')}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="postListingsStatusBar">
        {postsWithSize.length} items, {formatBytes(totalBytes)}
      </div>
    </div>
  );
}

export default function PostListingsWindow() {
  return (
    <ClassicyApp
      id={POST_LISTINGS_APP_ID}
      name="Posts"
      icon={ClassicyIcons.system.drives.disk}
      noDesktopIcon
      defaultWindow={POST_LISTINGS_WINDOW_ID}
    >
      <ClassicyWindow
        id={POST_LISTINGS_WINDOW_ID}
        appId={POST_LISTINGS_APP_ID}
        title="Posts"
        icon={ClassicyIcons.system.drives.disk}
        initialSize={[560, 340]}
        initialPosition={[250, 80]}
        resizable={false}
        zoomable={true}
        collapsable={true}
        defaultWindow
      >
        <PostListingsTable />
      </ClassicyWindow>
    </ClassicyApp>
  );
}
