import { notFound } from 'next/navigation';
// @ts-ignore - generated by Velite
import { posts } from '../../../.velite';
import ClassicyShell from '../../components/ClassicyShell';

type Post = { slug: string };

export function generateStaticParams() {
  return (posts as Post[]).map((post) => ({ slug: post.slug }));
}

export default async function PostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const found = (posts as Post[]).find((p) => p.slug === slug);
  if (!found) notFound();
  return <ClassicyShell initialSlug={slug} />;
}
