// @ts-ignore - generated by Velite
import { posts } from '../.velite';
import ClassicyShell from './components/ClassicyShell';

type Post = { slug: string; date: string };

export default function Home() {
  const sorted = (posts as Post[])
    .slice()
    .sort((a, b) => b.date.localeCompare(a.date));
  const latestSlug = sorted[0]?.slug ?? '';
  return <ClassicyShell initialSlug={latestSlug} />;
}
