import { describe, test, expect } from 'vitest';
// @ts-ignore - Will be generated by Velite
import { posts } from '../../.velite';

describe('Content Pipeline', () => {
  test('posts are generated correctly', () => {
    expect(posts).toBeDefined();
    expect(Array.isArray(posts)).toBe(true);
    expect(posts.length).toBe(3);

    const helloClassicy = posts.find((p: any) => p.slug === 'hello-classicy');
    expect(helloClassicy).toBeDefined();
    expect(helloClassicy!.title).toBe('Hello, Classicy');
    expect(typeof helloClassicy!.body).toBe('string');
    expect(helloClassicy!.date).toBeDefined();

    const typographyTest = posts.find((p: any) => p.slug === 'typography-test');
    expect(typographyTest).toBeDefined();
    expect(typographyTest!.title).toBe('Typography Test');
    expect(typeof typographyTest!.body).toBe('string');
    expect(typographyTest!.date).toBeDefined();
  });
});
